blueprint:
  name: Zone Occupation
  author: Colorful Cookie
  description: Simple zone occupation boolean switcher automation
  domain: automation
  input:
    person:
      name: Person
      description: The is the persons who's location is going to be used for the control.
      selector:
        entity:
          filter:
            - domain:
                - person
          multiple: true
    zone:
      name: Zone
      description:
        This zone will be used together with the persons to decide weather
        a thermostat should be on or off.
      selector:
        entity:
          filter:
            - domain:
                - zone
          multiple: false
    home_occupied:
      name: Input Boolean Occupied
      description:
        An input boolean that should changes its state based on the occupation
        of the zone from above.
      selector:
        entity:
          filter:
            - domain:
                - input_boolean
          multiple: false
  source_url: https://github.com/ColorfulCookie/HAT/blob/main/zone-occupation-boolean-control.yaml
trigger_variables:
  person: !input person
  zone: !input zone
  home_occupied: !input home_occupied
trigger:
  - platform: zone
    entity_id: !input person
    zone: !input zone
    event: enter
    id: enter
  - platform: zone
    entity_id: !input person
    zone: !input zone
    event: leave
    id: leave
  - platform: state
    entity_id: !input person
    from: null
    to: null
    id: state-change
variables:
  person: !input person
  zone: !input zone
  home_occupied: !input home_occupied
condition:
action:
  - if:
      - condition: trigger
        id: hat-start
    then:
      - delay:
          seconds: 30
  - choose:
      - conditions:
          - condition: not
            conditions:
              - condition: zone
                entity_id: !input person
                zone: !input zone
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.home_occupied
    default:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.home_occupied
